eeprom-decoder:  Fix build error on GCC10+
With GCC10+, the following build error occurs:

multiple definition of `id_data'; main.o:main.c:18: first defined here

The structure is defined as a global variable to the file,
but it's only referenced in main().
Move the struction declaration inside main the fix the build error.